Update train-bert.yml

diff --git a/.github/workflows/train-bert.yml b/.github/workflows/train-bert.yml
--- a/.github/workflows/train-bert.yml
+++ b/.github/workflows/train-bert.yml
@@ -33,14 +33,15 @@ jobs:
           AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
           AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
         run: |
-          az ml environment create --file cpu-environment.yml --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || echo "CPU Environment already exists or update failed"
+          az extension add -n ml -y
+          az ml environment create --conda-file cpu-environment.yml --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || echo "CPU Environment already exists or update failed"
 
       - name: Create or Update GPU Environment
         env:
           AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
           AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
         run: |
-          az ml environment create --file gpu-environment.yml --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || echo "GPU Environment already exists or update failed"
+          az ml environment create --conda-file gpu-environment.yml --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || echo "GPU Environment already exists or update failed"
 
       - name: Download Kaggle Dataset
         env:
@@ -55,7 +56,6 @@ jobs:
           AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
           AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
         run: |
-          az extension add -n ml -y
           az ml data create --name imdb-data --type uri_folder --path ./data --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
 
       - name: Submit Azure ML Job
